/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.test.slayer.service.persistence.iProjectPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the iProject service. Represents a row in the &quot;iproject_iproject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.slayer.model.impl.iProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.slayer.model.impl.iProjectImpl}.
 * </p>
 *
 * @author anshu
 * @see iProject
 * @see com.test.slayer.model.impl.iProjectImpl
 * @see com.test.slayer.model.impl.iProjectModelImpl
 * @generated
 */
public interface iProjectModel extends BaseModel<iProject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a i project model instance should use the {@link iProject} interface instead.
	 */

	/**
	 * Returns the primary key of this i project.
	 *
	 * @return the primary key of this i project
	 */
	public iProjectPK getPrimaryKey();

	/**
	 * Sets the primary key of this i project.
	 *
	 * @param primaryKey the primary key of this i project
	 */
	public void setPrimaryKey(iProjectPK primaryKey);

	/**
	 * Returns the project i d of this i project.
	 *
	 * @return the project i d of this i project
	 */
	public long getProjectID();

	/**
	 * Sets the project i d of this i project.
	 *
	 * @param projectID the project i d of this i project
	 */
	public void setProjectID(long projectID);

	/**
	 * Returns the project name of this i project.
	 *
	 * @return the project name of this i project
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this i project.
	 *
	 * @param projectName the project name of this i project
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the skillset of this i project.
	 *
	 * @return the skillset of this i project
	 */
	@AutoEscape
	public String getSkillset();

	/**
	 * Sets the skillset of this i project.
	 *
	 * @param skillset the skillset of this i project
	 */
	public void setSkillset(String skillset);

	/**
	 * Returns the description of this i project.
	 *
	 * @return the description of this i project
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this i project.
	 *
	 * @param description the description of this i project
	 */
	public void setDescription(String description);

	/**
	 * Returns the contact of this i project.
	 *
	 * @return the contact of this i project
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this i project.
	 *
	 * @param contact the contact of this i project
	 */
	public void setContact(String contact);

	/**
	 * Returns the date added of this i project.
	 *
	 * @return the date added of this i project
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this i project.
	 *
	 * @param dateAdded the date added of this i project
	 */
	public void setDateAdded(Date dateAdded);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(iProject iProject);

	public int hashCode();

	public CacheModel<iProject> toCacheModel();

	public iProject toEscapedModel();

	public String toString();

	public String toXmlString();
}