/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.poly.asu.student.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.poly.asu.student.model.studentgeninfo;
import com.poly.asu.student.service.persistence.studentgeninfoPersistence;
import com.poly.asu.student.service.studentgeninfoLocalService;
import com.poly.asu.student.service.studentgeninfoService;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the studentgeninfo local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.poly.asu.student.service.impl.studentgeninfoLocalServiceImpl}.
 * </p>
 *
 * @author Shruthi
 * @see com.poly.asu.student.service.impl.studentgeninfoLocalServiceImpl
 * @see com.poly.asu.student.service.studentgeninfoLocalServiceUtil
 * @generated
 */
public abstract class studentgeninfoLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements studentgeninfoLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.poly.asu.student.service.studentgeninfoLocalServiceUtil} to access the studentgeninfo local service.
	 */

	/**
	 * Adds the studentgeninfo to the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentgeninfo the studentgeninfo
	 * @return the studentgeninfo that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public studentgeninfo addstudentgeninfo(studentgeninfo studentgeninfo)
		throws SystemException {
		studentgeninfo.setNew(true);

		return studentgeninfoPersistence.update(studentgeninfo, false);
	}

	/**
	 * Creates a new studentgeninfo with the primary key. Does not add the studentgeninfo to the database.
	 *
	 * @param studentgeninfoid the primary key for the new studentgeninfo
	 * @return the new studentgeninfo
	 */
	public studentgeninfo createstudentgeninfo(long studentgeninfoid) {
		return studentgeninfoPersistence.create(studentgeninfoid);
	}

	/**
	 * Deletes the studentgeninfo with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentgeninfoid the primary key of the studentgeninfo
	 * @return the studentgeninfo that was removed
	 * @throws PortalException if a studentgeninfo with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public studentgeninfo deletestudentgeninfo(long studentgeninfoid)
		throws PortalException, SystemException {
		return studentgeninfoPersistence.remove(studentgeninfoid);
	}

	/**
	 * Deletes the studentgeninfo from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentgeninfo the studentgeninfo
	 * @return the studentgeninfo that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public studentgeninfo deletestudentgeninfo(studentgeninfo studentgeninfo)
		throws SystemException {
		return studentgeninfoPersistence.remove(studentgeninfo);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(studentgeninfo.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return studentgeninfoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return studentgeninfoPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return studentgeninfoPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return studentgeninfoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public studentgeninfo fetchstudentgeninfo(long studentgeninfoid)
		throws SystemException {
		return studentgeninfoPersistence.fetchByPrimaryKey(studentgeninfoid);
	}

	/**
	 * Returns the studentgeninfo with the primary key.
	 *
	 * @param studentgeninfoid the primary key of the studentgeninfo
	 * @return the studentgeninfo
	 * @throws PortalException if a studentgeninfo with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public studentgeninfo getstudentgeninfo(long studentgeninfoid)
		throws PortalException, SystemException {
		return studentgeninfoPersistence.findByPrimaryKey(studentgeninfoid);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return studentgeninfoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the studentgeninfos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of studentgeninfos
	 * @param end the upper bound of the range of studentgeninfos (not inclusive)
	 * @return the range of studentgeninfos
	 * @throws SystemException if a system exception occurred
	 */
	public List<studentgeninfo> getstudentgeninfos(int start, int end)
		throws SystemException {
		return studentgeninfoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of studentgeninfos.
	 *
	 * @return the number of studentgeninfos
	 * @throws SystemException if a system exception occurred
	 */
	public int getstudentgeninfosCount() throws SystemException {
		return studentgeninfoPersistence.countAll();
	}

	/**
	 * Updates the studentgeninfo in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param studentgeninfo the studentgeninfo
	 * @return the studentgeninfo that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public studentgeninfo updatestudentgeninfo(studentgeninfo studentgeninfo)
		throws SystemException {
		return updatestudentgeninfo(studentgeninfo, true);
	}

	/**
	 * Updates the studentgeninfo in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param studentgeninfo the studentgeninfo
	 * @param merge whether to merge the studentgeninfo with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the studentgeninfo that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public studentgeninfo updatestudentgeninfo(studentgeninfo studentgeninfo,
		boolean merge) throws SystemException {
		studentgeninfo.setNew(false);

		return studentgeninfoPersistence.update(studentgeninfo, merge);
	}

	/**
	 * Returns the studentgeninfo local service.
	 *
	 * @return the studentgeninfo local service
	 */
	public studentgeninfoLocalService getstudentgeninfoLocalService() {
		return studentgeninfoLocalService;
	}

	/**
	 * Sets the studentgeninfo local service.
	 *
	 * @param studentgeninfoLocalService the studentgeninfo local service
	 */
	public void setstudentgeninfoLocalService(
		studentgeninfoLocalService studentgeninfoLocalService) {
		this.studentgeninfoLocalService = studentgeninfoLocalService;
	}

	/**
	 * Returns the studentgeninfo remote service.
	 *
	 * @return the studentgeninfo remote service
	 */
	public studentgeninfoService getstudentgeninfoService() {
		return studentgeninfoService;
	}

	/**
	 * Sets the studentgeninfo remote service.
	 *
	 * @param studentgeninfoService the studentgeninfo remote service
	 */
	public void setstudentgeninfoService(
		studentgeninfoService studentgeninfoService) {
		this.studentgeninfoService = studentgeninfoService;
	}

	/**
	 * Returns the studentgeninfo persistence.
	 *
	 * @return the studentgeninfo persistence
	 */
	public studentgeninfoPersistence getstudentgeninfoPersistence() {
		return studentgeninfoPersistence;
	}

	/**
	 * Sets the studentgeninfo persistence.
	 *
	 * @param studentgeninfoPersistence the studentgeninfo persistence
	 */
	public void setstudentgeninfoPersistence(
		studentgeninfoPersistence studentgeninfoPersistence) {
		this.studentgeninfoPersistence = studentgeninfoPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.poly.asu.student.model.studentgeninfo",
			studentgeninfoLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.poly.asu.student.model.studentgeninfo");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return studentgeninfo.class;
	}

	protected String getModelClassName() {
		return studentgeninfo.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = studentgeninfoPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = studentgeninfoLocalService.class)
	protected studentgeninfoLocalService studentgeninfoLocalService;
	@BeanReference(type = studentgeninfoService.class)
	protected studentgeninfoService studentgeninfoService;
	@BeanReference(type = studentgeninfoPersistence.class)
	protected studentgeninfoPersistence studentgeninfoPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private studentgeninfoLocalServiceClpInvoker _clpInvoker = new studentgeninfoLocalServiceClpInvoker();
}