/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.CreateTeams.slayer.model.impl;

import com.CreateTeams.slayer.model.CTS;
import com.CreateTeams.slayer.service.CTSLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CTS service. Represents a row in the &quot;CTS_CTS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CTSImpl}.
 * </p>
 *
 * @author zhengyan
 * @see CTSImpl
 * @see com.CreateTeams.slayer.model.CTS
 * @generated
 */
public abstract class CTSBaseImpl extends CTSModelImpl implements CTS {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a c t s model instance should use the {@link CTS} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			CTSLocalServiceUtil.addCTS(this);
		}
		else {
			CTSLocalServiceUtil.updateCTS(this);
		}
	}
}