/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.CreateTeams.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CTS service. Represents a row in the &quot;CTS_CTS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.CreateTeams.slayer.model.impl.CTSModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.CreateTeams.slayer.model.impl.CTSImpl}.
 * </p>
 *
 * @author zhengyan
 * @see CTS
 * @see com.CreateTeams.slayer.model.impl.CTSImpl
 * @see com.CreateTeams.slayer.model.impl.CTSModelImpl
 * @generated
 */
public interface CTSModel extends BaseModel<CTS> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a c t s model instance should use the {@link CTS} interface instead.
	 */

	/**
	 * Returns the primary key of this c t s.
	 *
	 * @return the primary key of this c t s
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this c t s.
	 *
	 * @param primaryKey the primary key of this c t s
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the team ID of this c t s.
	 *
	 * @return the team ID of this c t s
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this c t s.
	 *
	 * @param TeamId the team ID of this c t s
	 */
	public void setTeamId(long TeamId);

	/**
	 * Returns the team name of this c t s.
	 *
	 * @return the team name of this c t s
	 */
	@AutoEscape
	public String getTeamName();

	/**
	 * Sets the team name of this c t s.
	 *
	 * @param TeamName the team name of this c t s
	 */
	public void setTeamName(String TeamName);

	/**
	 * Returns the team members of this c t s.
	 *
	 * @return the team members of this c t s
	 */
	@AutoEscape
	public String getTeamMembers();

	/**
	 * Sets the team members of this c t s.
	 *
	 * @param TeamMembers the team members of this c t s
	 */
	public void setTeamMembers(String TeamMembers);

	/**
	 * Returns the date added of this c t s.
	 *
	 * @return the date added of this c t s
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this c t s.
	 *
	 * @param dateAdded the date added of this c t s
	 */
	public void setDateAdded(Date dateAdded);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CTS cts);

	public int hashCode();

	public CacheModel<CTS> toCacheModel();

	public CTS toEscapedModel();

	public String toString();

	public String toXmlString();
}