/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viewiProject.servicelayer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.viewiProject.servicelayer.model.viewprj;
import com.viewiProject.servicelayer.model.viewprjModel;
import com.viewiProject.servicelayer.model.viewprjSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the viewprj service. Represents a row in the &quot;project_projectdetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.viewiProject.servicelayer.model.viewprjModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link viewprjImpl}.
 * </p>
 *
 * @author Shruthi
 * @see viewprjImpl
 * @see com.viewiProject.servicelayer.model.viewprj
 * @see com.viewiProject.servicelayer.model.viewprjModel
 * @generated
 */
@JSON(strict = true)
public class viewprjModelImpl extends BaseModelImpl<viewprj>
	implements viewprjModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a viewprj model instance should use the {@link com.viewiProject.servicelayer.model.viewprj} interface instead.
	 */
	public static final String TABLE_NAME = "project_projectdetail";
	public static final Object[][] TABLE_COLUMNS = {
			{ "projectId", Types.BIGINT },
			{ "projectTitle", Types.VARCHAR },
			{ "projectdescription", Types.VARCHAR },
			{ "projectrequiredskill", Types.VARCHAR },
			{ "contact", Types.VARCHAR },
			{ "dateAdded", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table project_projectdetail (projectId LONG not null primary key,projectTitle VARCHAR(75) null,projectdescription VARCHAR(75) null,projectrequiredskill VARCHAR(75) null,contact VARCHAR(75) null,dateAdded DATE null)";
	public static final String TABLE_SQL_DROP = "drop table project_projectdetail";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.viewiProject.servicelayer.model.viewprj"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.viewiProject.servicelayer.model.viewprj"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static viewprj toModel(viewprjSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		viewprj model = new viewprjImpl();

		model.setProjectId(soapModel.getProjectId());
		model.setProjectTitle(soapModel.getProjectTitle());
		model.setProjectdescription(soapModel.getProjectdescription());
		model.setProjectrequiredskill(soapModel.getProjectrequiredskill());
		model.setContact(soapModel.getContact());
		model.setDateAdded(soapModel.getDateAdded());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<viewprj> toModels(viewprjSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<viewprj> models = new ArrayList<viewprj>(soapModels.length);

		for (viewprjSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.viewiProject.servicelayer.model.viewprj"));

	public viewprjModelImpl() {
	}

	public long getPrimaryKey() {
		return _projectId;
	}

	public void setPrimaryKey(long primaryKey) {
		setProjectId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_projectId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return viewprj.class;
	}

	public String getModelClassName() {
		return viewprj.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("projectId", getProjectId());
		attributes.put("projectTitle", getProjectTitle());
		attributes.put("projectdescription", getProjectdescription());
		attributes.put("projectrequiredskill", getProjectrequiredskill());
		attributes.put("contact", getContact());
		attributes.put("dateAdded", getDateAdded());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long projectId = (Long)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}

		String projectTitle = (String)attributes.get("projectTitle");

		if (projectTitle != null) {
			setProjectTitle(projectTitle);
		}

		String projectdescription = (String)attributes.get("projectdescription");

		if (projectdescription != null) {
			setProjectdescription(projectdescription);
		}

		String projectrequiredskill = (String)attributes.get(
				"projectrequiredskill");

		if (projectrequiredskill != null) {
			setProjectrequiredskill(projectrequiredskill);
		}

		String contact = (String)attributes.get("contact");

		if (contact != null) {
			setContact(contact);
		}

		Date dateAdded = (Date)attributes.get("dateAdded");

		if (dateAdded != null) {
			setDateAdded(dateAdded);
		}
	}

	@JSON
	public long getProjectId() {
		return _projectId;
	}

	public void setProjectId(long projectId) {
		_projectId = projectId;
	}

	@JSON
	public String getProjectTitle() {
		if (_projectTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _projectTitle;
		}
	}

	public void setProjectTitle(String projectTitle) {
		_projectTitle = projectTitle;
	}

	@JSON
	public String getProjectdescription() {
		if (_projectdescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _projectdescription;
		}
	}

	public void setProjectdescription(String projectdescription) {
		_projectdescription = projectdescription;
	}

	@JSON
	public String getProjectrequiredskill() {
		if (_projectrequiredskill == null) {
			return StringPool.BLANK;
		}
		else {
			return _projectrequiredskill;
		}
	}

	public void setProjectrequiredskill(String projectrequiredskill) {
		_projectrequiredskill = projectrequiredskill;
	}

	@JSON
	public String getContact() {
		if (_contact == null) {
			return StringPool.BLANK;
		}
		else {
			return _contact;
		}
	}

	public void setContact(String contact) {
		_contact = contact;
	}

	@JSON
	public Date getDateAdded() {
		return _dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		_dateAdded = dateAdded;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			viewprj.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public viewprj toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (viewprj)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		viewprjImpl viewprjImpl = new viewprjImpl();

		viewprjImpl.setProjectId(getProjectId());
		viewprjImpl.setProjectTitle(getProjectTitle());
		viewprjImpl.setProjectdescription(getProjectdescription());
		viewprjImpl.setProjectrequiredskill(getProjectrequiredskill());
		viewprjImpl.setContact(getContact());
		viewprjImpl.setDateAdded(getDateAdded());

		viewprjImpl.resetOriginalValues();

		return viewprjImpl;
	}

	public int compareTo(viewprj viewprj) {
		long primaryKey = viewprj.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		viewprj viewprj = null;

		try {
			viewprj = (viewprj)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = viewprj.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<viewprj> toCacheModel() {
		viewprjCacheModel viewprjCacheModel = new viewprjCacheModel();

		viewprjCacheModel.projectId = getProjectId();

		viewprjCacheModel.projectTitle = getProjectTitle();

		String projectTitle = viewprjCacheModel.projectTitle;

		if ((projectTitle != null) && (projectTitle.length() == 0)) {
			viewprjCacheModel.projectTitle = null;
		}

		viewprjCacheModel.projectdescription = getProjectdescription();

		String projectdescription = viewprjCacheModel.projectdescription;

		if ((projectdescription != null) && (projectdescription.length() == 0)) {
			viewprjCacheModel.projectdescription = null;
		}

		viewprjCacheModel.projectrequiredskill = getProjectrequiredskill();

		String projectrequiredskill = viewprjCacheModel.projectrequiredskill;

		if ((projectrequiredskill != null) &&
				(projectrequiredskill.length() == 0)) {
			viewprjCacheModel.projectrequiredskill = null;
		}

		viewprjCacheModel.contact = getContact();

		String contact = viewprjCacheModel.contact;

		if ((contact != null) && (contact.length() == 0)) {
			viewprjCacheModel.contact = null;
		}

		Date dateAdded = getDateAdded();

		if (dateAdded != null) {
			viewprjCacheModel.dateAdded = dateAdded.getTime();
		}
		else {
			viewprjCacheModel.dateAdded = Long.MIN_VALUE;
		}

		return viewprjCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{projectId=");
		sb.append(getProjectId());
		sb.append(", projectTitle=");
		sb.append(getProjectTitle());
		sb.append(", projectdescription=");
		sb.append(getProjectdescription());
		sb.append(", projectrequiredskill=");
		sb.append(getProjectrequiredskill());
		sb.append(", contact=");
		sb.append(getContact());
		sb.append(", dateAdded=");
		sb.append(getDateAdded());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.viewiProject.servicelayer.model.viewprj");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectTitle</column-name><column-value><![CDATA[");
		sb.append(getProjectTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectdescription</column-name><column-value><![CDATA[");
		sb.append(getProjectdescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectrequiredskill</column-name><column-value><![CDATA[");
		sb.append(getProjectrequiredskill());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contact</column-name><column-value><![CDATA[");
		sb.append(getContact());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateAdded</column-name><column-value><![CDATA[");
		sb.append(getDateAdded());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = viewprj.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			viewprj.class
		};
	private long _projectId;
	private String _projectTitle;
	private String _projectdescription;
	private String _projectrequiredskill;
	private String _contact;
	private Date _dateAdded;
	private viewprj _escapedModelProxy;
}