/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.poly.asu.student.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the studentgeninfo service. Represents a row in the &quot;Studentgeninfo_studentgeninfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.poly.asu.student.model.impl.studentgeninfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.poly.asu.student.model.impl.studentgeninfoImpl}.
 * </p>
 *
 * @author Shruthi
 * @see studentgeninfo
 * @see com.poly.asu.student.model.impl.studentgeninfoImpl
 * @see com.poly.asu.student.model.impl.studentgeninfoModelImpl
 * @generated
 */
public interface studentgeninfoModel extends BaseModel<studentgeninfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a studentgeninfo model instance should use the {@link studentgeninfo} interface instead.
	 */

	/**
	 * Returns the primary key of this studentgeninfo.
	 *
	 * @return the primary key of this studentgeninfo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this studentgeninfo.
	 *
	 * @param primaryKey the primary key of this studentgeninfo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the studentgeninfoid of this studentgeninfo.
	 *
	 * @return the studentgeninfoid of this studentgeninfo
	 */
	public long getStudentgeninfoid();

	/**
	 * Sets the studentgeninfoid of this studentgeninfo.
	 *
	 * @param studentgeninfoid the studentgeninfoid of this studentgeninfo
	 */
	public void setStudentgeninfoid(long studentgeninfoid);

	/**
	 * Returns the name of this studentgeninfo.
	 *
	 * @return the name of this studentgeninfo
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this studentgeninfo.
	 *
	 * @param name the name of this studentgeninfo
	 */
	public void setName(String name);

	/**
	 * Returns the asuid of this studentgeninfo.
	 *
	 * @return the asuid of this studentgeninfo
	 */
	public long getAsuid();

	/**
	 * Sets the asuid of this studentgeninfo.
	 *
	 * @param asuid the asuid of this studentgeninfo
	 */
	public void setAsuid(long asuid);

	/**
	 * Returns the department of this studentgeninfo.
	 *
	 * @return the department of this studentgeninfo
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this studentgeninfo.
	 *
	 * @param department the department of this studentgeninfo
	 */
	public void setDepartment(String department);

	/**
	 * Returns the level of this studentgeninfo.
	 *
	 * @return the level of this studentgeninfo
	 */
	public long getLevel();

	/**
	 * Sets the level of this studentgeninfo.
	 *
	 * @param level the level of this studentgeninfo
	 */
	public void setLevel(long level);

	/**
	 * Returns the cummulativegpa of this studentgeninfo.
	 *
	 * @return the cummulativegpa of this studentgeninfo
	 */
	public float getCummulativegpa();

	/**
	 * Sets the cummulativegpa of this studentgeninfo.
	 *
	 * @param cummulativegpa the cummulativegpa of this studentgeninfo
	 */
	public void setCummulativegpa(float cummulativegpa);

	/**
	 * Returns the loggedinuser ID of this studentgeninfo.
	 *
	 * @return the loggedinuser ID of this studentgeninfo
	 */
	public long getLoggedinuserId();

	/**
	 * Sets the loggedinuser ID of this studentgeninfo.
	 *
	 * @param loggedinuserId the loggedinuser ID of this studentgeninfo
	 */
	public void setLoggedinuserId(long loggedinuserId);

	/**
	 * Returns the create date of this studentgeninfo.
	 *
	 * @return the create date of this studentgeninfo
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this studentgeninfo.
	 *
	 * @param createDate the create date of this studentgeninfo
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this studentgeninfo.
	 *
	 * @return the modified date of this studentgeninfo
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this studentgeninfo.
	 *
	 * @param modifiedDate the modified date of this studentgeninfo
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(studentgeninfo studentgeninfo);

	public int hashCode();

	public CacheModel<studentgeninfo> toCacheModel();

	public studentgeninfo toEscapedModel();

	public String toString();

	public String toXmlString();
}