/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.teams.manualSelect.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Faculty service. Represents a row in the &quot;faculty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.poly.teams.manualSelect.slayer.model.impl.FacultyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.poly.teams.manualSelect.slayer.model.impl.FacultyImpl}.
 * </p>
 *
 * @author asingh64
 * @see Faculty
 * @see com.asu.poly.teams.manualSelect.slayer.model.impl.FacultyImpl
 * @see com.asu.poly.teams.manualSelect.slayer.model.impl.FacultyModelImpl
 * @generated
 */
public interface FacultyModel extends BaseModel<Faculty> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a faculty model instance should use the {@link Faculty} interface instead.
	 */

	/**
	 * Returns the primary key of this faculty.
	 *
	 * @return the primary key of this faculty
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this faculty.
	 *
	 * @param primaryKey the primary key of this faculty
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the faculty i d of this faculty.
	 *
	 * @return the faculty i d of this faculty
	 */
	public long getFacultyID();

	/**
	 * Sets the faculty i d of this faculty.
	 *
	 * @param facultyID the faculty i d of this faculty
	 */
	public void setFacultyID(long facultyID);

	/**
	 * Returns the asuid of this faculty.
	 *
	 * @return the asuid of this faculty
	 */
	@AutoEscape
	public String getAsuid();

	/**
	 * Sets the asuid of this faculty.
	 *
	 * @param asuid the asuid of this faculty
	 */
	public void setAsuid(String asuid);

	/**
	 * Returns the faculty name of this faculty.
	 *
	 * @return the faculty name of this faculty
	 */
	@AutoEscape
	public String getFacultyName();

	/**
	 * Sets the faculty name of this faculty.
	 *
	 * @param facultyName the faculty name of this faculty
	 */
	public void setFacultyName(String facultyName);

	/**
	 * Returns the faculty dept of this faculty.
	 *
	 * @return the faculty dept of this faculty
	 */
	@AutoEscape
	public String getFacultyDept();

	/**
	 * Sets the faculty dept of this faculty.
	 *
	 * @param facultyDept the faculty dept of this faculty
	 */
	public void setFacultyDept(String facultyDept);

	/**
	 * Returns the contact of this faculty.
	 *
	 * @return the contact of this faculty
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this faculty.
	 *
	 * @param contact the contact of this faculty
	 */
	public void setContact(String contact);

	/**
	 * Returns the date added of this faculty.
	 *
	 * @return the date added of this faculty
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this faculty.
	 *
	 * @param dateAdded the date added of this faculty
	 */
	public void setDateAdded(Date dateAdded);

	/**
	 * Returns the date modified of this faculty.
	 *
	 * @return the date modified of this faculty
	 */
	public Date getDateModified();

	/**
	 * Sets the date modified of this faculty.
	 *
	 * @param dateModified the date modified of this faculty
	 */
	public void setDateModified(Date dateModified);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Faculty faculty);

	public int hashCode();

	public CacheModel<Faculty> toCacheModel();

	public Faculty toEscapedModel();

	public String toString();

	public String toXmlString();
}