/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.slayer.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.test.slayer.model.iProject;
import com.test.slayer.service.iProjectLocalService;
import com.test.slayer.service.iProjectService;
import com.test.slayer.service.persistence.iProjectPK;
import com.test.slayer.service.persistence.iProjectPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the i project local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.test.slayer.service.impl.iProjectLocalServiceImpl}.
 * </p>
 *
 * @author anshu
 * @see com.test.slayer.service.impl.iProjectLocalServiceImpl
 * @see com.test.slayer.service.iProjectLocalServiceUtil
 * @generated
 */
public abstract class iProjectLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements iProjectLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.test.slayer.service.iProjectLocalServiceUtil} to access the i project local service.
	 */

	/**
	 * Adds the i project to the database. Also notifies the appropriate model listeners.
	 *
	 * @param iProject the i project
	 * @return the i project that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public iProject addiProject(iProject iProject) throws SystemException {
		iProject.setNew(true);

		return iProjectPersistence.update(iProject, false);
	}

	/**
	 * Creates a new i project with the primary key. Does not add the i project to the database.
	 *
	 * @param iProjectPK the primary key for the new i project
	 * @return the new i project
	 */
	public iProject createiProject(iProjectPK iProjectPK) {
		return iProjectPersistence.create(iProjectPK);
	}

	/**
	 * Deletes the i project with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param iProjectPK the primary key of the i project
	 * @return the i project that was removed
	 * @throws PortalException if a i project with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public iProject deleteiProject(iProjectPK iProjectPK)
		throws PortalException, SystemException {
		return iProjectPersistence.remove(iProjectPK);
	}

	/**
	 * Deletes the i project from the database. Also notifies the appropriate model listeners.
	 *
	 * @param iProject the i project
	 * @return the i project that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public iProject deleteiProject(iProject iProject) throws SystemException {
		return iProjectPersistence.remove(iProject);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(iProject.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return iProjectPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return iProjectPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return iProjectPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return iProjectPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public iProject fetchiProject(iProjectPK iProjectPK)
		throws SystemException {
		return iProjectPersistence.fetchByPrimaryKey(iProjectPK);
	}

	/**
	 * Returns the i project with the primary key.
	 *
	 * @param iProjectPK the primary key of the i project
	 * @return the i project
	 * @throws PortalException if a i project with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public iProject getiProject(iProjectPK iProjectPK)
		throws PortalException, SystemException {
		return iProjectPersistence.findByPrimaryKey(iProjectPK);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return iProjectPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the i projects.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of i projects
	 * @param end the upper bound of the range of i projects (not inclusive)
	 * @return the range of i projects
	 * @throws SystemException if a system exception occurred
	 */
	public List<iProject> getiProjects(int start, int end)
		throws SystemException {
		return iProjectPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of i projects.
	 *
	 * @return the number of i projects
	 * @throws SystemException if a system exception occurred
	 */
	public int getiProjectsCount() throws SystemException {
		return iProjectPersistence.countAll();
	}

	/**
	 * Updates the i project in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param iProject the i project
	 * @return the i project that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public iProject updateiProject(iProject iProject) throws SystemException {
		return updateiProject(iProject, true);
	}

	/**
	 * Updates the i project in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param iProject the i project
	 * @param merge whether to merge the i project with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the i project that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public iProject updateiProject(iProject iProject, boolean merge)
		throws SystemException {
		iProject.setNew(false);

		return iProjectPersistence.update(iProject, merge);
	}

	/**
	 * Returns the i project local service.
	 *
	 * @return the i project local service
	 */
	public iProjectLocalService getiProjectLocalService() {
		return iProjectLocalService;
	}

	/**
	 * Sets the i project local service.
	 *
	 * @param iProjectLocalService the i project local service
	 */
	public void setiProjectLocalService(
		iProjectLocalService iProjectLocalService) {
		this.iProjectLocalService = iProjectLocalService;
	}

	/**
	 * Returns the i project remote service.
	 *
	 * @return the i project remote service
	 */
	public iProjectService getiProjectService() {
		return iProjectService;
	}

	/**
	 * Sets the i project remote service.
	 *
	 * @param iProjectService the i project remote service
	 */
	public void setiProjectService(iProjectService iProjectService) {
		this.iProjectService = iProjectService;
	}

	/**
	 * Returns the i project persistence.
	 *
	 * @return the i project persistence
	 */
	public iProjectPersistence getiProjectPersistence() {
		return iProjectPersistence;
	}

	/**
	 * Sets the i project persistence.
	 *
	 * @param iProjectPersistence the i project persistence
	 */
	public void setiProjectPersistence(iProjectPersistence iProjectPersistence) {
		this.iProjectPersistence = iProjectPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.test.slayer.model.iProject",
			iProjectLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.test.slayer.model.iProject");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return iProject.class;
	}

	protected String getModelClassName() {
		return iProject.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = iProjectPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = iProjectLocalService.class)
	protected iProjectLocalService iProjectLocalService;
	@BeanReference(type = iProjectService.class)
	protected iProjectService iProjectService;
	@BeanReference(type = iProjectPersistence.class)
	protected iProjectPersistence iProjectPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private iProjectLocalServiceClpInvoker _clpInvoker = new iProjectLocalServiceClpInvoker();
}