/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.iproject.student.preferences.service.base;

import com.asu.poly.iproject.student.preferences.model.preferences;
import com.asu.poly.iproject.student.preferences.service.ProjectdetailLocalService;
import com.asu.poly.iproject.student.preferences.service.ProjectdetailService;
import com.asu.poly.iproject.student.preferences.service.persistence.ProjectdetailPersistence;
import com.asu.poly.iproject.student.preferences.service.persistence.preferencesPersistence;
import com.asu.poly.iproject.student.preferences.service.preferencesLocalService;
import com.asu.poly.iproject.student.preferences.service.preferencesService;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the preferences local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.asu.poly.iproject.student.preferences.service.impl.preferencesLocalServiceImpl}.
 * </p>
 *
 * @author asingh64
 * @see com.asu.poly.iproject.student.preferences.service.impl.preferencesLocalServiceImpl
 * @see com.asu.poly.iproject.student.preferences.service.preferencesLocalServiceUtil
 * @generated
 */
public abstract class preferencesLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements preferencesLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.asu.poly.iproject.student.preferences.service.preferencesLocalServiceUtil} to access the preferences local service.
	 */

	/**
	 * Adds the preferences to the database. Also notifies the appropriate model listeners.
	 *
	 * @param preferences the preferences
	 * @return the preferences that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public preferences addpreferences(preferences preferences)
		throws SystemException {
		preferences.setNew(true);

		return preferencesPersistence.update(preferences, false);
	}

	/**
	 * Creates a new preferences with the primary key. Does not add the preferences to the database.
	 *
	 * @param studentID the primary key for the new preferences
	 * @return the new preferences
	 */
	public preferences createpreferences(long studentID) {
		return preferencesPersistence.create(studentID);
	}

	/**
	 * Deletes the preferences with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentID the primary key of the preferences
	 * @return the preferences that was removed
	 * @throws PortalException if a preferences with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public preferences deletepreferences(long studentID)
		throws PortalException, SystemException {
		return preferencesPersistence.remove(studentID);
	}

	/**
	 * Deletes the preferences from the database. Also notifies the appropriate model listeners.
	 *
	 * @param preferences the preferences
	 * @return the preferences that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public preferences deletepreferences(preferences preferences)
		throws SystemException {
		return preferencesPersistence.remove(preferences);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(preferences.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return preferencesPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return preferencesPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return preferencesPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return preferencesPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public preferences fetchpreferences(long studentID)
		throws SystemException {
		return preferencesPersistence.fetchByPrimaryKey(studentID);
	}

	/**
	 * Returns the preferences with the primary key.
	 *
	 * @param studentID the primary key of the preferences
	 * @return the preferences
	 * @throws PortalException if a preferences with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public preferences getpreferences(long studentID)
		throws PortalException, SystemException {
		return preferencesPersistence.findByPrimaryKey(studentID);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return preferencesPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the preferenceses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of preferenceses
	 * @param end the upper bound of the range of preferenceses (not inclusive)
	 * @return the range of preferenceses
	 * @throws SystemException if a system exception occurred
	 */
	public List<preferences> getpreferenceses(int start, int end)
		throws SystemException {
		return preferencesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of preferenceses.
	 *
	 * @return the number of preferenceses
	 * @throws SystemException if a system exception occurred
	 */
	public int getpreferencesesCount() throws SystemException {
		return preferencesPersistence.countAll();
	}

	/**
	 * Updates the preferences in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param preferences the preferences
	 * @return the preferences that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public preferences updatepreferences(preferences preferences)
		throws SystemException {
		return updatepreferences(preferences, true);
	}

	/**
	 * Updates the preferences in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param preferences the preferences
	 * @param merge whether to merge the preferences with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the preferences that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public preferences updatepreferences(preferences preferences, boolean merge)
		throws SystemException {
		preferences.setNew(false);

		return preferencesPersistence.update(preferences, merge);
	}

	/**
	 * Returns the preferences local service.
	 *
	 * @return the preferences local service
	 */
	public preferencesLocalService getpreferencesLocalService() {
		return preferencesLocalService;
	}

	/**
	 * Sets the preferences local service.
	 *
	 * @param preferencesLocalService the preferences local service
	 */
	public void setpreferencesLocalService(
		preferencesLocalService preferencesLocalService) {
		this.preferencesLocalService = preferencesLocalService;
	}

	/**
	 * Returns the preferences remote service.
	 *
	 * @return the preferences remote service
	 */
	public preferencesService getpreferencesService() {
		return preferencesService;
	}

	/**
	 * Sets the preferences remote service.
	 *
	 * @param preferencesService the preferences remote service
	 */
	public void setpreferencesService(preferencesService preferencesService) {
		this.preferencesService = preferencesService;
	}

	/**
	 * Returns the preferences persistence.
	 *
	 * @return the preferences persistence
	 */
	public preferencesPersistence getpreferencesPersistence() {
		return preferencesPersistence;
	}

	/**
	 * Sets the preferences persistence.
	 *
	 * @param preferencesPersistence the preferences persistence
	 */
	public void setpreferencesPersistence(
		preferencesPersistence preferencesPersistence) {
		this.preferencesPersistence = preferencesPersistence;
	}

	/**
	 * Returns the projectdetail local service.
	 *
	 * @return the projectdetail local service
	 */
	public ProjectdetailLocalService getProjectdetailLocalService() {
		return projectdetailLocalService;
	}

	/**
	 * Sets the projectdetail local service.
	 *
	 * @param projectdetailLocalService the projectdetail local service
	 */
	public void setProjectdetailLocalService(
		ProjectdetailLocalService projectdetailLocalService) {
		this.projectdetailLocalService = projectdetailLocalService;
	}

	/**
	 * Returns the projectdetail remote service.
	 *
	 * @return the projectdetail remote service
	 */
	public ProjectdetailService getProjectdetailService() {
		return projectdetailService;
	}

	/**
	 * Sets the projectdetail remote service.
	 *
	 * @param projectdetailService the projectdetail remote service
	 */
	public void setProjectdetailService(
		ProjectdetailService projectdetailService) {
		this.projectdetailService = projectdetailService;
	}

	/**
	 * Returns the projectdetail persistence.
	 *
	 * @return the projectdetail persistence
	 */
	public ProjectdetailPersistence getProjectdetailPersistence() {
		return projectdetailPersistence;
	}

	/**
	 * Sets the projectdetail persistence.
	 *
	 * @param projectdetailPersistence the projectdetail persistence
	 */
	public void setProjectdetailPersistence(
		ProjectdetailPersistence projectdetailPersistence) {
		this.projectdetailPersistence = projectdetailPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.asu.poly.iproject.student.preferences.model.preferences",
			preferencesLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.asu.poly.iproject.student.preferences.model.preferences");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return preferences.class;
	}

	protected String getModelClassName() {
		return preferences.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = preferencesPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = preferencesLocalService.class)
	protected preferencesLocalService preferencesLocalService;
	@BeanReference(type = preferencesService.class)
	protected preferencesService preferencesService;
	@BeanReference(type = preferencesPersistence.class)
	protected preferencesPersistence preferencesPersistence;
	@BeanReference(type = ProjectdetailLocalService.class)
	protected ProjectdetailLocalService projectdetailLocalService;
	@BeanReference(type = ProjectdetailService.class)
	protected ProjectdetailService projectdetailService;
	@BeanReference(type = ProjectdetailPersistence.class)
	protected ProjectdetailPersistence projectdetailPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private preferencesLocalServiceClpInvoker _clpInvoker = new preferencesLocalServiceClpInvoker();
}