/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.iproject.student.skillset.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Skillset service. Represents a row in the &quot;Skillset_Skillset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.iproject.student.skillset.model.impl.SkillsetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.iproject.student.skillset.model.impl.SkillsetImpl}.
 * </p>
 *
 * @author zhengyan
 * @see Skillset
 * @see com.asu.iproject.student.skillset.model.impl.SkillsetImpl
 * @see com.asu.iproject.student.skillset.model.impl.SkillsetModelImpl
 * @generated
 */
public interface SkillsetModel extends BaseModel<Skillset> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skillset model instance should use the {@link Skillset} interface instead.
	 */

	/**
	 * Returns the primary key of this skillset.
	 *
	 * @return the primary key of this skillset
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skillset.
	 *
	 * @param primaryKey the primary key of this skillset
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student i d of this skillset.
	 *
	 * @return the student i d of this skillset
	 */
	public long getStudentID();

	/**
	 * Sets the student i d of this skillset.
	 *
	 * @param studentID the student i d of this skillset
	 */
	public void setStudentID(long studentID);

	/**
	 * Returns the asuid of this skillset.
	 *
	 * @return the asuid of this skillset
	 */
	@AutoEscape
	public String getAsuid();

	/**
	 * Sets the asuid of this skillset.
	 *
	 * @param asuid the asuid of this skillset
	 */
	public void setAsuid(String asuid);

	/**
	 * Returns the email of this skillset.
	 *
	 * @return the email of this skillset
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this skillset.
	 *
	 * @param email the email of this skillset
	 */
	public void setEmail(String email);

	/**
	 * Returns the skill1 of this skillset.
	 *
	 * @return the skill1 of this skillset
	 */
	@AutoEscape
	public String getSkill1();

	/**
	 * Sets the skill1 of this skillset.
	 *
	 * @param skill1 the skill1 of this skillset
	 */
	public void setSkill1(String skill1);

	/**
	 * Returns the date added of this skillset.
	 *
	 * @return the date added of this skillset
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this skillset.
	 *
	 * @param dateAdded the date added of this skillset
	 */
	public void setDateAdded(Date dateAdded);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Skillset skillset);

	public int hashCode();

	public CacheModel<Skillset> toCacheModel();

	public Skillset toEscapedModel();

	public String toString();

	public String toXmlString();
}