/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.viewiProject.servicelayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the viewprj service. Represents a row in the &quot;project_projectdetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.viewiProject.servicelayer.model.impl.viewprjModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.viewiProject.servicelayer.model.impl.viewprjImpl}.
 * </p>
 *
 * @author Shruthi
 * @see viewprj
 * @see com.viewiProject.servicelayer.model.impl.viewprjImpl
 * @see com.viewiProject.servicelayer.model.impl.viewprjModelImpl
 * @generated
 */
public interface viewprjModel extends BaseModel<viewprj> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a viewprj model instance should use the {@link viewprj} interface instead.
	 */

	/**
	 * Returns the primary key of this viewprj.
	 *
	 * @return the primary key of this viewprj
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this viewprj.
	 *
	 * @param primaryKey the primary key of this viewprj
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project ID of this viewprj.
	 *
	 * @return the project ID of this viewprj
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this viewprj.
	 *
	 * @param projectId the project ID of this viewprj
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the project title of this viewprj.
	 *
	 * @return the project title of this viewprj
	 */
	@AutoEscape
	public String getProjectTitle();

	/**
	 * Sets the project title of this viewprj.
	 *
	 * @param projectTitle the project title of this viewprj
	 */
	public void setProjectTitle(String projectTitle);

	/**
	 * Returns the projectdescription of this viewprj.
	 *
	 * @return the projectdescription of this viewprj
	 */
	@AutoEscape
	public String getProjectdescription();

	/**
	 * Sets the projectdescription of this viewprj.
	 *
	 * @param projectdescription the projectdescription of this viewprj
	 */
	public void setProjectdescription(String projectdescription);

	/**
	 * Returns the projectrequiredskill of this viewprj.
	 *
	 * @return the projectrequiredskill of this viewprj
	 */
	@AutoEscape
	public String getProjectrequiredskill();

	/**
	 * Sets the projectrequiredskill of this viewprj.
	 *
	 * @param projectrequiredskill the projectrequiredskill of this viewprj
	 */
	public void setProjectrequiredskill(String projectrequiredskill);

	/**
	 * Returns the contact of this viewprj.
	 *
	 * @return the contact of this viewprj
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this viewprj.
	 *
	 * @param contact the contact of this viewprj
	 */
	public void setContact(String contact);

	/**
	 * Returns the date added of this viewprj.
	 *
	 * @return the date added of this viewprj
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this viewprj.
	 *
	 * @param dateAdded the date added of this viewprj
	 */
	public void setDateAdded(Date dateAdded);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(viewprj viewprj);

	public int hashCode();

	public CacheModel<viewprj> toCacheModel();

	public viewprj toEscapedModel();

	public String toString();

	public String toXmlString();
}