/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.teams.manualSelect.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Student service. Represents a row in the &quot;student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.poly.teams.manualSelect.slayer.model.impl.StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.poly.teams.manualSelect.slayer.model.impl.StudentImpl}.
 * </p>
 *
 * @author Eshwari
 * @see Student
 * @see com.asu.poly.teams.manualSelect.slayer.model.impl.StudentImpl
 * @see com.asu.poly.teams.manualSelect.slayer.model.impl.StudentModelImpl
 * @generated
 */
public interface StudentModel extends BaseModel<Student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link Student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student i d of this student.
	 *
	 * @return the student i d of this student
	 */
	public long getStudentID();

	/**
	 * Sets the student i d of this student.
	 *
	 * @param studentID the student i d of this student
	 */
	public void setStudentID(long studentID);

	/**
	 * Returns the asuid of this student.
	 *
	 * @return the asuid of this student
	 */
	@AutoEscape
	public String getAsuid();

	/**
	 * Sets the asuid of this student.
	 *
	 * @param asuid the asuid of this student
	 */
	public void setAsuid(String asuid);

	/**
	 * Returns the student name of this student.
	 *
	 * @return the student name of this student
	 */
	@AutoEscape
	public String getStudentName();

	/**
	 * Sets the student name of this student.
	 *
	 * @param studentName the student name of this student
	 */
	public void setStudentName(String studentName);

	/**
	 * Returns the level of this student.
	 *
	 * @return the level of this student
	 */
	@AutoEscape
	public String getLevel();

	/**
	 * Sets the level of this student.
	 *
	 * @param level the level of this student
	 */
	public void setLevel(String level);

	/**
	 * Returns the course of this student.
	 *
	 * @return the course of this student
	 */
	@AutoEscape
	public String getCourse();

	/**
	 * Sets the course of this student.
	 *
	 * @param course the course of this student
	 */
	public void setCourse(String course);

	/**
	 * Returns the gpa of this student.
	 *
	 * @return the gpa of this student
	 */
	@AutoEscape
	public String getGpa();

	/**
	 * Sets the gpa of this student.
	 *
	 * @param gpa the gpa of this student
	 */
	public void setGpa(String gpa);

	/**
	 * Returns the sex of this student.
	 *
	 * @return the sex of this student
	 */
	@AutoEscape
	public String getSex();

	/**
	 * Sets the sex of this student.
	 *
	 * @param sex the sex of this student
	 */
	public void setSex(String sex);

	/**
	 * Returns the date added of this student.
	 *
	 * @return the date added of this student
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this student.
	 *
	 * @param dateAdded the date added of this student
	 */
	public void setDateAdded(Date dateAdded);

	/**
	 * Returns the date modified of this student.
	 *
	 * @return the date modified of this student
	 */
	public Date getDateModified();

	/**
	 * Sets the date modified of this student.
	 *
	 * @param dateModified the date modified of this student
	 */
	public void setDateModified(Date dateModified);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Student student);

	public int hashCode();

	public CacheModel<Student> toCacheModel();

	public Student toEscapedModel();

	public String toString();

	public String toXmlString();
}