/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.teams.manualSelect.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Team service. Represents a row in the &quot;TeamDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.poly.teams.manualSelect.slayer.model.impl.TeamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.poly.teams.manualSelect.slayer.model.impl.TeamImpl}.
 * </p>
 *
 * @author Eshwari
 * @see Team
 * @see com.asu.poly.teams.manualSelect.slayer.model.impl.TeamImpl
 * @see com.asu.poly.teams.manualSelect.slayer.model.impl.TeamModelImpl
 * @generated
 */
public interface TeamModel extends BaseModel<Team> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team model instance should use the {@link Team} interface instead.
	 */

	/**
	 * Returns the primary key of this team.
	 *
	 * @return the primary key of this team
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this team.
	 *
	 * @param primaryKey the primary key of this team
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the team i d of this team.
	 *
	 * @return the team i d of this team
	 */
	public long getTeamID();

	/**
	 * Sets the team i d of this team.
	 *
	 * @param teamID the team i d of this team
	 */
	public void setTeamID(long teamID);

	/**
	 * Returns the project title of this team.
	 *
	 * @return the project title of this team
	 */
	@AutoEscape
	public String getProjectTitle();

	/**
	 * Sets the project title of this team.
	 *
	 * @param projectTitle the project title of this team
	 */
	public void setProjectTitle(String projectTitle);

	/**
	 * Returns the faculty1 of this team.
	 *
	 * @return the faculty1 of this team
	 */
	@AutoEscape
	public String getFaculty1();

	/**
	 * Sets the faculty1 of this team.
	 *
	 * @param faculty1 the faculty1 of this team
	 */
	public void setFaculty1(String faculty1);

	/**
	 * Returns the faculty2 of this team.
	 *
	 * @return the faculty2 of this team
	 */
	@AutoEscape
	public String getFaculty2();

	/**
	 * Sets the faculty2 of this team.
	 *
	 * @param faculty2 the faculty2 of this team
	 */
	public void setFaculty2(String faculty2);

	/**
	 * Returns the faculty3 of this team.
	 *
	 * @return the faculty3 of this team
	 */
	@AutoEscape
	public String getFaculty3();

	/**
	 * Sets the faculty3 of this team.
	 *
	 * @param faculty3 the faculty3 of this team
	 */
	public void setFaculty3(String faculty3);

	/**
	 * Returns the faculty4 of this team.
	 *
	 * @return the faculty4 of this team
	 */
	@AutoEscape
	public String getFaculty4();

	/**
	 * Sets the faculty4 of this team.
	 *
	 * @param faculty4 the faculty4 of this team
	 */
	public void setFaculty4(String faculty4);

	/**
	 * Returns the student0 of this team.
	 *
	 * @return the student0 of this team
	 */
	@AutoEscape
	public String getStudent0();

	/**
	 * Sets the student0 of this team.
	 *
	 * @param student0 the student0 of this team
	 */
	public void setStudent0(String student0);

	/**
	 * Returns the student1 of this team.
	 *
	 * @return the student1 of this team
	 */
	@AutoEscape
	public String getStudent1();

	/**
	 * Sets the student1 of this team.
	 *
	 * @param student1 the student1 of this team
	 */
	public void setStudent1(String student1);

	/**
	 * Returns the student2 of this team.
	 *
	 * @return the student2 of this team
	 */
	@AutoEscape
	public String getStudent2();

	/**
	 * Sets the student2 of this team.
	 *
	 * @param student2 the student2 of this team
	 */
	public void setStudent2(String student2);

	/**
	 * Returns the student3 of this team.
	 *
	 * @return the student3 of this team
	 */
	@AutoEscape
	public String getStudent3();

	/**
	 * Sets the student3 of this team.
	 *
	 * @param student3 the student3 of this team
	 */
	public void setStudent3(String student3);

	/**
	 * Returns the student4 of this team.
	 *
	 * @return the student4 of this team
	 */
	@AutoEscape
	public String getStudent4();

	/**
	 * Sets the student4 of this team.
	 *
	 * @param student4 the student4 of this team
	 */
	public void setStudent4(String student4);

	/**
	 * Returns the student5 of this team.
	 *
	 * @return the student5 of this team
	 */
	@AutoEscape
	public String getStudent5();

	/**
	 * Sets the student5 of this team.
	 *
	 * @param student5 the student5 of this team
	 */
	public void setStudent5(String student5);

	/**
	 * Returns the student6 of this team.
	 *
	 * @return the student6 of this team
	 */
	@AutoEscape
	public String getStudent6();

	/**
	 * Sets the student6 of this team.
	 *
	 * @param student6 the student6 of this team
	 */
	public void setStudent6(String student6);

	/**
	 * Returns the student7 of this team.
	 *
	 * @return the student7 of this team
	 */
	@AutoEscape
	public String getStudent7();

	/**
	 * Sets the student7 of this team.
	 *
	 * @param student7 the student7 of this team
	 */
	public void setStudent7(String student7);

	/**
	 * Returns the student8 of this team.
	 *
	 * @return the student8 of this team
	 */
	@AutoEscape
	public String getStudent8();

	/**
	 * Sets the student8 of this team.
	 *
	 * @param student8 the student8 of this team
	 */
	public void setStudent8(String student8);

	/**
	 * Returns the student9 of this team.
	 *
	 * @return the student9 of this team
	 */
	@AutoEscape
	public String getStudent9();

	/**
	 * Sets the student9 of this team.
	 *
	 * @param student9 the student9 of this team
	 */
	public void setStudent9(String student9);

	/**
	 * Returns the date added of this team.
	 *
	 * @return the date added of this team
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this team.
	 *
	 * @param dateAdded the date added of this team
	 */
	public void setDateAdded(Date dateAdded);

	/**
	 * Returns the date modified of this team.
	 *
	 * @return the date modified of this team
	 */
	public Date getDateModified();

	/**
	 * Sets the date modified of this team.
	 *
	 * @param dateModified the date modified of this team
	 */
	public void setDateModified(Date dateModified);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Team team);

	public int hashCode();

	public CacheModel<Team> toCacheModel();

	public Team toEscapedModel();

	public String toString();

	public String toXmlString();
}