/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.addfacultypreferences.slayer.service.base;

import com.addfacultypreferences.slayer.model.LNSBook;
import com.addfacultypreferences.slayer.service.LNSBookLocalService;
import com.addfacultypreferences.slayer.service.persistence.LNSBookPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the l n s book local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.addfacultypreferences.slayer.service.impl.LNSBookLocalServiceImpl}.
 * </p>
 *
 * @author Eshwari
 * @see com.addfacultypreferences.slayer.service.impl.LNSBookLocalServiceImpl
 * @see com.addfacultypreferences.slayer.service.LNSBookLocalServiceUtil
 * @generated
 */
public abstract class LNSBookLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements LNSBookLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.addfacultypreferences.slayer.service.LNSBookLocalServiceUtil} to access the l n s book local service.
	 */

	/**
	 * Adds the l n s book to the database. Also notifies the appropriate model listeners.
	 *
	 * @param lnsBook the l n s book
	 * @return the l n s book that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public LNSBook addLNSBook(LNSBook lnsBook) throws SystemException {
		lnsBook.setNew(true);

		return lnsBookPersistence.update(lnsBook, false);
	}

	/**
	 * Creates a new l n s book with the primary key. Does not add the l n s book to the database.
	 *
	 * @param nameId the primary key for the new l n s book
	 * @return the new l n s book
	 */
	public LNSBook createLNSBook(long nameId) {
		return lnsBookPersistence.create(nameId);
	}

	/**
	 * Deletes the l n s book with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param nameId the primary key of the l n s book
	 * @return the l n s book that was removed
	 * @throws PortalException if a l n s book with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public LNSBook deleteLNSBook(long nameId)
		throws PortalException, SystemException {
		return lnsBookPersistence.remove(nameId);
	}

	/**
	 * Deletes the l n s book from the database. Also notifies the appropriate model listeners.
	 *
	 * @param lnsBook the l n s book
	 * @return the l n s book that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public LNSBook deleteLNSBook(LNSBook lnsBook) throws SystemException {
		return lnsBookPersistence.remove(lnsBook);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(LNSBook.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return lnsBookPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return lnsBookPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return lnsBookPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return lnsBookPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public LNSBook fetchLNSBook(long nameId) throws SystemException {
		return lnsBookPersistence.fetchByPrimaryKey(nameId);
	}

	/**
	 * Returns the l n s book with the primary key.
	 *
	 * @param nameId the primary key of the l n s book
	 * @return the l n s book
	 * @throws PortalException if a l n s book with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public LNSBook getLNSBook(long nameId)
		throws PortalException, SystemException {
		return lnsBookPersistence.findByPrimaryKey(nameId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return lnsBookPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the l n s books.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of l n s books
	 * @param end the upper bound of the range of l n s books (not inclusive)
	 * @return the range of l n s books
	 * @throws SystemException if a system exception occurred
	 */
	public List<LNSBook> getLNSBooks(int start, int end)
		throws SystemException {
		return lnsBookPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of l n s books.
	 *
	 * @return the number of l n s books
	 * @throws SystemException if a system exception occurred
	 */
	public int getLNSBooksCount() throws SystemException {
		return lnsBookPersistence.countAll();
	}

	/**
	 * Updates the l n s book in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param lnsBook the l n s book
	 * @return the l n s book that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public LNSBook updateLNSBook(LNSBook lnsBook) throws SystemException {
		return updateLNSBook(lnsBook, true);
	}

	/**
	 * Updates the l n s book in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param lnsBook the l n s book
	 * @param merge whether to merge the l n s book with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the l n s book that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public LNSBook updateLNSBook(LNSBook lnsBook, boolean merge)
		throws SystemException {
		lnsBook.setNew(false);

		return lnsBookPersistence.update(lnsBook, merge);
	}

	/**
	 * Returns the l n s book local service.
	 *
	 * @return the l n s book local service
	 */
	public LNSBookLocalService getLNSBookLocalService() {
		return lnsBookLocalService;
	}

	/**
	 * Sets the l n s book local service.
	 *
	 * @param lnsBookLocalService the l n s book local service
	 */
	public void setLNSBookLocalService(LNSBookLocalService lnsBookLocalService) {
		this.lnsBookLocalService = lnsBookLocalService;
	}

	/**
	 * Returns the l n s book persistence.
	 *
	 * @return the l n s book persistence
	 */
	public LNSBookPersistence getLNSBookPersistence() {
		return lnsBookPersistence;
	}

	/**
	 * Sets the l n s book persistence.
	 *
	 * @param lnsBookPersistence the l n s book persistence
	 */
	public void setLNSBookPersistence(LNSBookPersistence lnsBookPersistence) {
		this.lnsBookPersistence = lnsBookPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.addfacultypreferences.slayer.model.LNSBook",
			lnsBookLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.addfacultypreferences.slayer.model.LNSBook");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return LNSBook.class;
	}

	protected String getModelClassName() {
		return LNSBook.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = lnsBookPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LNSBookLocalService.class)
	protected LNSBookLocalService lnsBookLocalService;
	@BeanReference(type = LNSBookPersistence.class)
	protected LNSBookPersistence lnsBookPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private LNSBookLocalServiceClpInvoker _clpInvoker = new LNSBookLocalServiceClpInvoker();
}