/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.iproject.student.preferences.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the preferences service. Represents a row in the &quot;student_preferences&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.poly.iproject.student.preferences.model.impl.preferencesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.poly.iproject.student.preferences.model.impl.preferencesImpl}.
 * </p>
 *
 * @author asingh64
 * @see preferences
 * @see com.asu.poly.iproject.student.preferences.model.impl.preferencesImpl
 * @see com.asu.poly.iproject.student.preferences.model.impl.preferencesModelImpl
 * @generated
 */
public interface preferencesModel extends BaseModel<preferences> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a preferences model instance should use the {@link preferences} interface instead.
	 */

	/**
	 * Returns the primary key of this preferences.
	 *
	 * @return the primary key of this preferences
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this preferences.
	 *
	 * @param primaryKey the primary key of this preferences
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student i d of this preferences.
	 *
	 * @return the student i d of this preferences
	 */
	public long getStudentID();

	/**
	 * Sets the student i d of this preferences.
	 *
	 * @param studentID the student i d of this preferences
	 */
	public void setStudentID(long studentID);

	/**
	 * Returns the a s u i d of this preferences.
	 *
	 * @return the a s u i d of this preferences
	 */
	@AutoEscape
	public String getASUID();

	/**
	 * Sets the a s u i d of this preferences.
	 *
	 * @param ASUID the a s u i d of this preferences
	 */
	public void setASUID(String ASUID);

	/**
	 * Returns the preference1 of this preferences.
	 *
	 * @return the preference1 of this preferences
	 */
	@AutoEscape
	public String getPreference1();

	/**
	 * Sets the preference1 of this preferences.
	 *
	 * @param preference1 the preference1 of this preferences
	 */
	public void setPreference1(String preference1);

	/**
	 * Returns the preference2 of this preferences.
	 *
	 * @return the preference2 of this preferences
	 */
	@AutoEscape
	public String getPreference2();

	/**
	 * Sets the preference2 of this preferences.
	 *
	 * @param preference2 the preference2 of this preferences
	 */
	public void setPreference2(String preference2);

	/**
	 * Returns the preference3 of this preferences.
	 *
	 * @return the preference3 of this preferences
	 */
	@AutoEscape
	public String getPreference3();

	/**
	 * Sets the preference3 of this preferences.
	 *
	 * @param preference3 the preference3 of this preferences
	 */
	public void setPreference3(String preference3);

	/**
	 * Returns the preference4 of this preferences.
	 *
	 * @return the preference4 of this preferences
	 */
	@AutoEscape
	public String getPreference4();

	/**
	 * Sets the preference4 of this preferences.
	 *
	 * @param preference4 the preference4 of this preferences
	 */
	public void setPreference4(String preference4);

	/**
	 * Returns the preference5 of this preferences.
	 *
	 * @return the preference5 of this preferences
	 */
	@AutoEscape
	public String getPreference5();

	/**
	 * Sets the preference5 of this preferences.
	 *
	 * @param preference5 the preference5 of this preferences
	 */
	public void setPreference5(String preference5);

	/**
	 * Returns the date added of this preferences.
	 *
	 * @return the date added of this preferences
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this preferences.
	 *
	 * @param dateAdded the date added of this preferences
	 */
	public void setDateAdded(Date dateAdded);

	/**
	 * Returns the date modified of this preferences.
	 *
	 * @return the date modified of this preferences
	 */
	public Date getDateModified();

	/**
	 * Sets the date modified of this preferences.
	 *
	 * @param dateModified the date modified of this preferences
	 */
	public void setDateModified(Date dateModified);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(preferences preferences);

	public int hashCode();

	public CacheModel<preferences> toCacheModel();

	public preferences toEscapedModel();

	public String toString();

	public String toXmlString();
}